[dev]
  functions = "functions"
  publish = "client/build"
[build]
  functions = "functions"
  publish = "client/build"
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200