[build]
  command = "netlify-lambda build api && cd client && npm install && npm run build"
  Functions = "functions"
  Publish = "client/build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200